### ISSUE TITLE
HTML structure changes when a class or id is added.

### ISSUE THREAD

**Issue by sharu725** [allejo/jekyll-toc#1]
Normal TOC structure without class or id.
```
<ul>
  <li><a href="#ut-libero-elit">Ut libero elit</a></li>
  <li><a href="#in-hac-habitasse-platea-dictumst">In hac habitasse platea dictumst.</a>
    <ul>
      <li><a href="#duis-tristique-enim-quis">Duis tristique enim quis</a></li>
    </ul>
  </li>
</ul>
```

TOC with class or id

```
<ul class="toc">
  <li><a href="#ut-libero-elit">Ut libero elit</a>
    <ul>
      <li><a href="#in-hac-habitasse-platea-dictumst">In hac habitasse platea dictumst.</a>
        <ul>
          <li><a href="#duis-tristique-enim-quis">Duis tristique enim quis</a></li>
        </ul>
      </li>
    </ul>
  </li>
</ul>
```

I hope this can be fixed.

**Comment by allejo** [comment]
Would you mind sharing what your markdown looks like? The headings specifically and their respective order.

**Comment by sharu725** [comment]
Sure. Here are the headings.
```
## Ut libero elit
## In hac habitasse platea dictumst.
### Duis tristique enim quis
```

**Comment by allejo** [comment]
Do all your headings start at 2 or is it just this particular markdown? If all your headings start at 2, as a temporary workaround, if you set `h_min` to 2, then it should fix the issue.

However, I will fix this issue as soon as I can.

**Comment by sharu725** [comment]
@allejo thank you very much for this toc. `h_min=2` fixed it and all my headings start wih h2. I will be recommending this to other people.

**Comment by allejo** [comment]
[Version 1.0.1 released](https://github.com/allejo/jekyll-toc/releases/tag/v1.0.1) along with some added unit tests:

- [headings starting at 2 with a class](https://github.com/allejo/jekyll-toc/blob/master/_tests/headingsStartingAtTwoWithClass.md)
- [headings starting at 2 without a class](https://github.com/allejo/jekyll-toc/blob/master/_tests/headingsStartingAtTwoWithoutClass.md)

Thanks for the bug report!
