### ISSUE TITLE
Fix to work with headings that are links

### ISSUE THREAD

**Issue by JTuwiner** [allejo/jekyll-toc#11]
**My Markdown**

`[The Zinus Ironline Metal and Wood Platform Bed with Headboard](https://www.amazon.com/gp/product/B075FGY7G2/)`

**TOC Usage**

`{% include toc.html html=content h_min=2 h_max=2 %}`

**Expected TOC**

`<a href="#the-zinus-ironline-metal-and-wood-platform-bed-with-headboardhttpswwwamazoncomgpproductb075fgy7g2">The Zinus Ironline Metal and Wood Platform Bed with Headboard</a>`

**Actual TOC**

`<a href="#the-zinus-ironline-metal-and-wood-platform-bed-with-headboardhttpswwwamazoncomgpproductb075fgy7g2"></a><a href="https://www.amazon.com/gp/product/B075FGY7G2/">The Zinus Ironline Metal and Wood Platform Bed with Headboard</a>`

**Notes**

First off, this is an absolutely awesome plugin! I've been looking for something that will allow me to only include H2s in the TOCs. 

My issue here is my headings are URLs, but for some reason in the TOC the links go to the URL instead of the # tag. It's actually generating two <a> tags, one which is empty and one which just goes to the URL and not the heading. How can I fix this?

**Comment by allejo** [comment]
Sure thing! Glad I could help and that this snippet met your needs 😄
