### ISSUE TITLE
Allow defining title

### ISSUE THREAD

**Issue by caliburn1994** [allejo/jekyll-toc#20]
```html
{% include toc.html html=content title="Contents" title_class="toctitle" title_id="toctitle_id"%}
```
such as [Wikipedia](https://en.wikipedia.org/wiki/Wiki)

**Comment by allejo** [comment]
I feel that adding the option to render a title for the TOC can become too opinionated and should be left up to the developer/designer instead. This is why the snippet generates only the absolute minimum needed for a TOC by default.

Achieving what you want can be as simple as creating something like this in your own Jekyll theme:

```twig
<section>
    <header>
        <h2 id="toctitle_id" class="toctitle">Contents</h2>
    </header>
    
    {% include toc.html html=content %}
</section>
```

or

```twig
<div>
    <p><strong id="toctitle_id" class="toctitle">Contents</strong></p>

    {% include toc.html html=content %}
</div>
```

There's so much room for preference here that I lean towards towards BYOS (Bring Your Own Styles) 👍
