### ISSUE TITLE
Disable in a Special Post

### ISSUE THREAD

**Issue by KiarashS** [allejo/jekyll-toc#30]
Thanks for `jekyll-toc`.
Please add a future to disable `jekyll-toc` in a Special Post via `Front Matter`.

For example:

```
---
layout: post
title: "Welcome to Jekyll!"
toc: false
---
```

**Comment by hszhakka** [comment]
You could yourself decide whether to include the `toc` template:

```liquid
{% if page.toc %}
  {% include toc.html html=content %}
{% endif %}
```

**Comment by allejo** [comment]
This feature is out of the scope of this project. The correct solution is what @hszhakka posted: handling the logic to disable this at the layout level.
