### ISSUE TITLE
Incompatibility with "GFM" parser

### ISSUE THREAD

**Issue by chrisyeh96** [allejo/jekyll-toc#46]
TOC version 1.0.14

I am using GitHub Pages. In the `_config.yml` file, if I set (see [GitHub docs](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/setting-a-markdown-processor-for-your-github-pages-site-using-jekyll))

```yml
markdown: gfm  # as opposed to the default "kramdown"
```

then the TOC liquid template's various `*_class` parameters become problematic. This is because the TOC liquid template assumes that the markdown processor supports [*inline attribute lists*](https://kramdown.gettalong.org/syntax.html#inline-attribute-lists). kramdown supports this, but GFM does not.

Consequently, if my markdown file includes the following line,

```markdown
{% include toc.html html=content anchor_class="nav-link" %}
```

then the output looks like

```html
<ul>
<li><a href="#some-header">Some Header</a>{:.nav-link}
</ul>
```

instead of the desired

```html
<ul>
<li><a href="#some-header" class="nav-link">Some Header</a>
</ul>
```

To the best of my (limited) knowledge on this subject, I think that the solution would require that you work with HTML `<ul>` and `<li>` elements directly, instead of simply converting every heading `<hX>` into a markdown-syntax list of links and then calling `markdownify`. I understand that this would require quite a significant change to the existing liquid template, but I really hope that you would be willing to implement this change!

For background context, the reason why I would like to use the GFM parser as opposed to kramdown is because kramdown handles math syntax in a very idiosyncratic way (see my blog post [here](https://chrisyeh96.github.io/2020/03/29/mathjax3.html)). If I can use the GFM parser instead of kramdown, it would make my math syntax much simpler!

**Comment by allejo** [comment]
I've never used the `gfm` markdown parser so I've got a few questions. What's the difference between these two?

```yaml
# Option 1
markdown: gfm
```

and

```yaml
# Option 2
markdown: kramdown
kramdown:
  input: GFM
```

I ask because when I do Option 2, the following markdown is valid and gets parsed correctly.

```markdown
- [ ] Testing
- {: class='foobar' style='list-style-type: none'} [x] Testing 2
```

However, when I do Option 1, the following markdown (which should be valid GFM, I think?) doesn't work:

```markdown
- [ ] Testing
- [x] Testing 2
```

**Comment by chrisyeh96** [comment]
GitHub Pages supports two Markdown parsers: GFM and kramdown. See [here](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/setting-a-markdown-processor-for-your-github-pages-site-using-jekyll).

### GFM Parser
```yml
markdown: gfm
```
The GFM parser (in theory) matches the formal specifications described in the [GFM specification](https://github.github.com/gfm/). GFM stands for GitHub-Flavored Markdown, which is a superset of the CommonMark specification. Notably, the GFM specification does not include inline attribute lists.

### Kramdown Parser with GFM input
```yml
markdown: kramdown
```
The [kramdown syntax](https://kramdown.gettalong.org/syntax.html) is similar (but not identical) to GFM. As the kramdown syntax page documentation specifically [mentions](https://kramdown.gettalong.org/syntax.html#inline-attribute-lists) about attribute lists,
> This syntax feature is not part of the original Markdown syntax. The idea and syntax comes from the Maruku package.

**Comment by allejo** [comment]
Got it! Thanks for the clarification between the two markdown parsers, clears up a lot.

I have a vague idea on what changes will be needed for this project to achieve this, they don't seem like too much fun :sweat_smile: Let me draw things out a bit more clearly and see where to go from there. But yea I'm open to revisiting building out a TOC via HTML instead of markdown.

**Comment by chrisyeh96** [comment]
Thanks @allejo! It isn't the end of the world if you don't have time to make this change, but it would definitely improve compatibility moving forward, especially as CommonMark and its extensions (like GFM) becomes more popular over time.

If you do decide to make this change, would you mind giving an estimated time that this would take? Days? Weeks? It would help me plan around that!

**Comment by allejo** [comment]
> If you do decide to make this change, would you mind giving an estimated time that this would take? Days? Weeks? It would help me plan around that!

Given what's currently on my plate, probably a few weeks at the earliest.

**Comment by mosabua** [comment]
I am finding a similar problem when using CommonMark as markdown parser. With it on there are no links created on the ToC and there are a couple of characters emitted at the bottom of the ToC.

As soon as I switch over to kramdown it all works. Should I file a separate ticket? Can I maybe help somehow? 

Just for reference I am trying to use commonmark and liquid/liquid-c from shopify to improve build performance. Currently its not an issue yet but I am planning for getting a rather large site in place..

**Comment by allejo** [comment]
Take a look at the latest `develop` branch (and PR #52), which completely changes how the ToC is generated. All of my existing unit tests are passing but if you're able to find problems, please report them.

The develop branch currently is planned to be the next stable release, so see if this fixes your problem too, @mosabua

**Comment by chrisyeh96** [comment]
@allejo Just tested out the latest version (1.1.0-dev), looks great to me! Thank you so much for putting in the effort!

**Comment by mosabua** [comment]
Wow... amazing work @allejo 

I looks like I might be missing something. I do not get any links using CommonMark. I have a feeling the reason is that I used jekyll-toc together with jekyll-anchor-headings .. which does not seem to work with CommonMark .. so for me its back to kramdown for now. I am not inserting any ids manually at this stage. 

If I do convert a title from 
 
    ## title

to

    <h2 id="myid">title</h2>

it works like a charm.

**Comment by allejo** [comment]
If links are not being generated, the first thing to check is making sure that the generated headings in your HTML have `id` attributes. Neither jekyll-toc or jekyll-anchor-headings add IDs to headings, this is left up to the markdown renderer (kramdown, GFM, CommonMark).

**Comment by mosabua** [comment]
Awesome. Thanks. I might have to see how to convince CommonMark to do that.
