### ISSUE TITLE
toc is generated for the previous page (filename, alphabetically)

### ISSUE THREAD

**Issue by popindavibe** [allejo/jekyll-toc#48]
**Markdown Engine**

kramdown

Write here.

**My Markdown**

```markdown
---
layout: page
namespace: tos
title: titles.tos
permalink: /tos/
permalink_fr: /cgu/
toc: true
tags: terms-of-service tos agreement
---

{% include toc.html html=content %}

{% translate_file pages/main/tos.md %}
```

**TOC Usage**

```twig
{% include toc.html html=content %}
```

**Expected TOC**

A TOC of the current page

**Actual TOC**

The TOC of the previous page

**Notes**

I'm pretty sure the issue is not with your script, since I have the exact same issue when trying with the `jekyll-toc` plugin. But I have no idea why I am getting this behaviour, as everything else works fine.

**Comment by allejo** [comment]
Do you have an example repository with this problem? There's not enough in the issue for me to determine what's going on.

**Comment by popindavibe** [comment]
Sorry, I don't have it around. I just found out that TOC is supported natively in Jekyll Kramdown, and that I just needed to use unnumbered list and `{:toc}`. This proved to work fine to build a TOC of the page's content.

```
* My TOC here
{:toc}
```

I was hoping you may have faced that issue before, looking for a quick pointer. Anyway my issue is considered fixed, don't want to spend more time on it. Thanks.

**Comment by benlk** [comment]
I encountered this issue when putting the following not in a template file, but in a markdown file:

```
{% include toc.html html=content h_max=3 ordered=true id="toc" %}
```

The "bug" probably arises from trying to render the `include` before the page's markdown has been rendered and becomes available within the `content` variable.

`page.content` doesn't have HTML tags for detection, so I got around this "bug" by rendering the markdown into a temporary variable:

```
{% assign temp_content = page.content | markdownify %}
{% include toc.html html=temp_content h_max=3 ordered=true id="toc" %}
```
