### ISSUE TITLE
make jekyll-toc working with twbs/bootstrap

### ISSUE THREAD

**Issue by m5o** [allejo/jekyll-toc#5]
Hey @allejo 👋 

The popular [twbs/bootstrap](https://github.com/twbs/bootstrap) repo is currently using a [custom plugin](https://github.com/toshimaru/jekyll-toc) for generating the toc. 
With your help, we could replace the old custom toc with your `jekyll-toc` which has out-of-the-box support for github-pages.
I wanted to ask, if you want to help make jekyll-toc ready to be replaced in bootstrap.

I've made a branch in my fork an played a bit:
https://github.com/m5o/bootstrap/tree/jekyll-toc

**TOC Usage**

```liquid
{% include toc.html html=content class="section-nav" h_min=1 h_max=4 %}
```

**Expected TOC**

```html
<!-- from: https://getbootstrap.com/docs/4.0/components/alerts/ -->
<ul class="section-nav">
  <li class="toc-entry toc-h2"><a href="#examples">Examples</a>
    <ul>
      <li class="toc-entry toc-h3"><a href="#link-color">Link color</a></li>
      <li class="toc-entry toc-h3"><a href="#additional-content">Additional content</a>
        <ul>
          <li class="toc-entry toc-h4"><a href="#well-done">Well done!</a></li>
        </ul>
      </li>
      <li class="toc-entry toc-h3"><a href="#dismissing">Dismissing</a></li>
    </ul>
  </li>
  <li class="toc-entry toc-h2"><a href="#javascript-behavior">JavaScript behavior</a>
    <ul>
      <li class="toc-entry toc-h3"><a href="#triggers">Triggers</a></li>
      <li class="toc-entry toc-h3"><a href="#methods">Methods</a></li>
      <li class="toc-entry toc-h3"><a href="#events">Events</a></li>
    </ul>
  </li>
</ul>
```

**Actual TOC**

```html
<ul class="section-nav">
  <li><a href="#examples">Examples</a>
    <ul>
      <li><a href="#link-color">Link color</a></li>
      <li><a href="#additional-content">Additional content</a></li>
      <li><a href="#dismissing">Dismissing</a></li>
    </ul>
  </li>
  <li><a href="#javascript-behavior">JavaScript behavior</a>
    <ul>
      <li><a href="#triggers">Triggers</a></li>
      <li><a href="#methods">Methods</a></li>
      <li><a href="#events">Events</a></li>
    </ul>
  </li>
</ul>
```

**ToDos**

* the `li` have custom classes including the level `toc-entry hX`
* spotted jekyll-toc includes the headline ("Conveying meaning to assistive technologies") of the [callout box](https://getbootstrap.com/docs/4.0/components/alerts/#conveying-meaning-to-assistive-technologies)

**Comment by allejo** [comment]
Hi there 👋 

The feature you're asking for should be doable.

For what it's worth, using this project on the Bootstrap website has been tried in the past and it was decided not to continue with this solution: see #3. Not sure if requirements on that matter have changed or not.

**Comment by m5o** [comment]
Time has passed, progress was made. Together with @XhmikosR we nuked some custom plugins lately. Only two open task ahead

**Comment by XhmikosR** [comment]
I'm not sure we can do this @m5o. I have already tried it and it ended up being a lot messier.

It's OK to keep one or two plugins. The problem is with the custom plugins in the repo; those slow down things the most.

**Comment by m5o** [comment]
@XhmikosR It would be really valuable, because it will be allow usage of github-pages support out-of-the-box. This is a huge thing.

**Comment by XhmikosR** [comment]
There is a balance between every thing. And here, personally, it just is more complex than it has to be.

We don't really care to make the docs build on GitHub pages. It's an extra step we have learned to live with.

But, if we can get rid of the custom plugins (not gems) then at least the build should speed up. Either way this is outside of this repo's scope :)

**Comment by m5o** [comment]
> We don't really care to make the docs build on GitHub pages. It's an extra step we have learned to live with.

It could get 57.000+ forks the possibility to rollout a docs page. This will benefit the bootstrap environment a lot.

**Comment by XhmikosR** [comment]
I don't see any benefit there. Also, our gh-pages branch includes older docs versions. We just can't use GitHub pages.

**Comment by allejo** [comment]
I could see this feature request being useful to others, so [here's how to use it](https://raw.githubusercontent.com/allejo/jekyll-toc/master/_tests/listItemWithCustomClass.md).
