### ISSUE TITLE
Just a little hint from a rookie

### ISSUE THREAD

**Issue by warbe-maker** [allejo/jekyll-toc#51]
I tried a lot to manage a true working download link an finally ended up with:
[_mTrc_](https://gitcdn.link/repo/warbe-maker/Common-VBA-Error-Handler/master/mTrc.bas)
\[_mTrc_\](https://gitcdn.link/repo/warbe-maker/Common-VBA-Error-Handler/master/mTrc.bas)

This gitcdn (https://gitcdn.link/repo/) followed by your repo is the one and only solution which works when your write Download followed by a link - specifically because it ensures that only the latest version from master is downloaded. Everything else is cumbersome specifically for those not a 100% familiar with github repos.

I hope you'll appreaciate this.

**Comment by allejo** [comment]
I've always posted a copy of `toc.html` on the Releases page. So instead of relying on an external service, I'll just link to both the latest release and the master branch.

Fixed in 6f23f19aeb543ef985c85fd9e715d3cd43df4d3f

Thank you for the suggestion! :smile:
