### ISSUE TITLE
Not working with Jekyll CommonMark

### ISSUE THREAD

**Issue by xplosionmind** [allejo/jekyll-toc#55]
**Markdown Engine**: [jekyll-commonmark](https://github.com/jekyll/jekyll-commonmark "Jekyll CommonMark plugin on GitHub")
jekyll-toc version: 1.1.0

## My Markdown

```markdown
## Improvements and fixes
### Nextcloud
## Installed
## Mail server
### options
## Wishlist
## General knowledge
## Docker
## DIY Home Server
### Raspberry Pi
```

## TOC Usage

```twig
{% include toc.html html=content sanitize="true" %}
```

## Expected TOC

```html
<ul>
<li><a href="#improvements-and-fixes">Improvements and fixes</a><ul><li><a href="#nextcloud">Nextcloud</a></li></ul></li>
<li><a href="#installed">Installed</a></li>
<li>
<a href="#mail-server">Mail server</a><ul><li><a href="#options">options</a></li></ul>
</li>
<li><a href="#wishlist">Wishlist</a></li>
<li><a href="#general-knowledge">General knowledge</a></li>
<li><a href="#docker">Docker</a></li>
<li>
<a href="#diy-home-server">DIY Home Server</a><ul><li><a href="#raspberry-pi">Raspberry Pi</a></li></ul>
</li>
</ul>
```

## Actual TOC

```html
<ul>
<li>Improvements and fixes<ul><li>Nextcloud</li></ul>
</li>
<li>Installed</li>
<li>Mail server<ul><li>options</li></ul>
</li>
<li>Wishlist</li>
<li>General knowledge</li>
<li>Docker</li>
<li>DIY Home Server<ul><li>Raspberry Pi</li></ul>
</li>
</ul>
```

## Notes

Only the naked list items are displayed, without any `a` tag.   
I'm sorry if the HTML looks bad but it's minified.

**Comment by allejo** [comment]
This is a limitation with Jekyll's CommonMark implementation that does not automatically insert `id`s to headings. See https://github.com/jekyll/jekyll-commonmark/issues/41

This snippet doesn't generate any IDs or touch the headings, so it doesn't know how to link to them. I'm afraid there's not much this project can do about this 😐

**Comment by allejo** [comment]
If you're using CommonMark and aren't getting your IDs generated, you can look at the [`generateId` parameter of our sister project `jekyll-anchor-headings`](https://github.com/allejo/jekyll-anchor-headings#parameters). So long as your anchor tags that are generated are empty, and you strip HTML for jekyll-toc, things should render just fine.
