### ISSUE TITLE
TOC links are not generated with Commonmark

### ISSUE THREAD

**Issue by xplosionmind** [allejo/jekyll-toc#63]
**Markdown Engine**

Commonmark

**My Markdown**

```markdown
## Why

Text

<br>
<br>

## Log

- list
- list

<br>

### WIP

- list
- list

<br>
<br>

## Resources
```

**TOC Usage**

```twig
{% include toc.html html=content %}
```

**Expected TOC**

```html
<div id="toc">
<h3>Table of contents</h3>
<ul>
<li><a href='#why'>Why</a></li>
<li><a href='#log'>Log</a><ul><li><a href='#wip'>WIP</a></li></ul>
</li>
<li><a href='#resources'>Resources</a></li>
</ul>
</div>
```

**Actual TOC**

```html
<div id="toc">
<h3>Table of contents</h3>
<ul>
<li>Why</li>
<li>Log<ul><li>WIP</li></ul>
</li>
<li>Resources</li>
</ul>
</div>
```

**Notes**

I don’t know if it is me not including a parameter I should or if it is a limit from of the TOC parser. Apparently, what has been fixed in [jekyll-anchor-headings](https://github.com/allejo/jekyll-anchor-headings/) [1.0.10](https://github.com/allejo/jekyll-anchor-headings/releases/tag/v1.0.10) has not been fixed for jekyll-toc.

**Comment by allejo** [comment]
Hi, welcome back 👋 

See https://github.com/allejo/jekyll-toc/issues/55#issuecomment-927585063 lol

jekyll-toc doesn't modify content like jekyll-anchor-headings, so it's not a feature that this project can implement.

**Comment by xplosionmind** [comment]
Hi! I am so sorry I forgot about that duplicate issue I opened. So you are telling me there is no way to “pass” the headings generated by jekyll-anchor-headings (which are generated just fine) to jekyll-toc, so that it can parse links starting from them?

**Comment by allejo** [comment]
Ah I see what you mean! That should work as based on my comment. Let's say you have the following right now,

```liquid
{% include toc.html html=content %}

<section class="main-body">
  {% include anchor_headings.html html=content generateId=true %}
</section>
```

What you will need to do is capture the results and feed the results into `jekyll-toc`.

```liquid
{% capture processed_content %}
  {% include anchor_headings.html html=content generateId=true %}
{% endcapture %}

{% include toc.html html=processed_content %}

<section class="main-body">
  {{ processed_content }}
</section>
```

**Comment by xplosionmind** [comment]
This works wonderfully. Thank you very much!

Best, Tommi.
