### ISSUE TITLE
Allow non-nested lists

### ISSUE THREAD

**Issue by M3T1N** [allejo/jekyll-toc#70]
Is it possible to get a non-nested list? Nested lists like this one create problems when writing CSS (especially using :nth-of-type())

```html
<ul>
    <li>
        <a href="#heading-1" class="anchor_class">Heading 1</a>
        <ul>
            <li>
                <a href="#heading-21" class="anchor_class">Heading 2.1</a>
            </li>
            <li>
                <a href="#heading-22" class="anchor_class">Heading 2.2</a>
            </li>
        </ul>
    </li>
</ul>
```

It would be great if it was possible to get lists like this one:

```html
<ul>
    <li>
        <a href="#heading-1" class="anchor_class">Heading 1</a>
    </li>
    <li>
        <a href="#heading-21" class="anchor_class">Heading 2.1</a>
    </li>
    <li>
        <a href="#heading-22" class="anchor_class">Heading 2.2</a>
    </li>
</ul>
```
If it is already possible, how could I use that? If it is not, please add a feature for this. I'm sorry for my English, I try my best :)

**Comment by allejo** [comment]
It is currently not possible to achieve this but also, shouldn't be hard to implement.

I am curious as to why you need everything only at one level? Is it just because the CSS is hard to write?

**Comment by allejo** [comment]
I've added a new `flat_toc` parameter that you can use to opt-in to having a single-level table of contents; tagged in v1.2.1
