### ISSUE TITLE
Skipping levels or not starting at the lowest level causes "promotion" of headers, or omission entirely

### ISSUE THREAD

**Issue by JakeSteam** [allejo/jekyll-toc#72]
**Markdown Engine**

Kramdown

**My Markdown**

```
## a

## b

#### c

## d
```

**TOC Usage**

```
{% include custom/contents.html html=content sanitize=true h_max=4 %}
```

**Expected TOC**

```html
<ul>
    <li><a href="#a">a</a></li>
    <li>
        <a href="#b">b</a>
        <ul>
            <li><a href="#c">c</a></li>
        </ul>
    </li>
    <li><a href="#d">d</a></li>
</ul>
```

**Actual TOC**

```html
<ul>
    <li><a href="#a">a</a></li>
    <li>
        <a href="#b">b</a>
        <ul>
            <li><a href="#c">c</a></li>
        </ul>
    </li>
</ul>
</li>
<li><a href="#d">d</a></li>
</ul>
```

**Notes**

Hey, this is a very edge case bug, but raising it for completeness. I made a mistake in an article and accidentally used H4s instead of H3s, hence discovering this by accident.

If for whatever reason you skip a layer (e.g. going H2 -> H4), a subsequent H2 header will "escape" the main `ul`. There are a few other symptoms / related scenarios I could find, I suspect the same root cause:
1. In my example, if `## d` was `### d`, it gets "promoted" into an H2. 
2. In my example, if `## a` and `## b` are omitted, `## d` disappears entirely. This can be done with just `## a` & `# b`.

Elements disappearing entirely is obviously due to line 110 & `firstHeader`, but I had a little play with the logic and couldn't spot anything obvious causing the "promotion" issue. 

Thanks for the great liquid script!

**Comment by allejo** [comment]
Thank you for the report! This is a common issue that a lot of people run into, and I could have sworn I had written a section into the README, but turns out I never pushed it.

Anyways, this is intended behavior as describe in the new section of the README,

https://github.com/allejo/jekyll-toc#an-li-is-rendering-outside-of-a-ul
