### ISSUE TITLE
TOC  as columns?

### ISSUE THREAD

**Issue by Gabriel-p** [allejo/jekyll-toc#73]
**Description**

I have too many headings and they spill outside of the page.

![Captura de pantalla de 2023-12-04 10 25 57](https://github.com/allejo/jekyll-toc/assets/6054951/86142344-8911-43e9-97dc-09efc66b3401)

It'd be great if I could select to split the single large list into X columns.

**Sample Usage**

```twig
{% include toc.html html=content columns=3 %}
```

**Expected TOC**

Not sure, I'm not a developer sorry.

```html

```

**Comment by allejo** [comment]
You can achieve this entirely via CSS! Use the [`columns` CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/columns) and here's [an example of how it's used](https://www.w3schools.com/css/css3_multiple_columns.asp).
