### ISSUE TITLE
TOC generated only on selected posts

### ISSUE THREAD

**Issue by edoardottt** [allejo/jekyll-toc#74]
**Description**

With https://github.com/toshimaru/jekyll-toc (that as now it doesn't work for GitHub Pages) it's possible to add a selector in the post settings and select for which posts the table of contents must be shown.

**Sample Usage**

e.g.

```markdown
---
published: true
title: example title
layout: post
tags:
  - example
categories:
  - example
permalink: example
toc: true
---
```
It's possible to define `toc: true/false` to decide in the post markdown content if the TOC should be generated or not.

As far as I know this isn't working for this repository. 

**Expected TOC**

- `toc: true`: HTML TOC generated
- `toc: false`: HTML TOC not generated

**Comment by allejo** [comment]
This project has nothing to do with the YAML frontmatter and only works with the Jekyll-generated HTML. What you can do in your theme though is, if the `toc` frontmatter is true, give the heading the ".no_toc" class (as per #21), and that heading will be excluded from the generated TOC.

**Comment by edoardottt** [comment]
Thanks @allejo for the quick reply and sorry for misunderstanding!

I'm new to jekyll, sorry again. What do you mean with `in your theme` ?  
I guess something like this (using CSS selectors for markdown):
```markdown
### Heading3
{: .no-toc }
```

If this is the case it won't be good as I need the TOC only for 1 post and ignore it for all the others.
Adding a class for all the headings in all other posts won't be easy.
That's why I mentioned the YAML frontmatter selector.

**Comment by allejo** [comment]
Take a look at the Minimal Mistakes Jekyll theme, which makes use of this project. If you put `toc: false` in your front matter, you can access that from your Liquid templates via `page.toc` like so,

https://github.com/mmistakes/minimal-mistakes/blob/6f5e6f43911c0283bd029040a4b22d3d31fe3c30/_layouts/single.html#L42-L53

Based on whether or not that variable is set, that's where you can choose to include the `toc.html`
